/********************************************************************
* hparticleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error hparticleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablehparticleDict();
extern void G__cpp_setup_inheritancehparticleDict();
extern void G__cpp_setup_typetablehparticleDict();
extern void G__cpp_setup_memvarhparticleDict();
extern void G__cpp_setup_globalhparticleDict();
extern void G__cpp_setup_memfunchparticleDict();
extern void G__cpp_setup_funchparticleDict();
extern void G__set_cpp_environmenthparticleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THParticle.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__hparticleDictLN_TClass;
extern G__linked_taginfo G__hparticleDictLN_TBuffer;
extern G__linked_taginfo G__hparticleDictLN_TMemberInspector;
extern G__linked_taginfo G__hparticleDictLN_TObject;
extern G__linked_taginfo G__hparticleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__hparticleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hparticleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__hparticleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__hparticleDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__hparticleDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__hparticleDictLN_TLorentzVector;
extern G__linked_taginfo G__hparticleDictLN_TAttLine;
extern G__linked_taginfo G__hparticleDictLN_TAtt3D;
extern G__linked_taginfo G__hparticleDictLN_TParticle;
extern G__linked_taginfo G__hparticleDictLN_THParticle;

/* STUB derived class for protected member access */
